'use client';
import {useEffect,useMemo,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {KnowledgeEditor,type Membership} from '@/modules/admin/knowledge-editor';
import {AnalyticsRepository,type AnalyticsGranularity,type AnalyticsReport,type AnalyticsRecommendation} from '@/modules/admin/analytics';

type Preset='today'|'week'|'month'|'custom';
type View='analytics'|'recommendations';
const emptyReport:AnalyticsReport={summary:{customers:0,chats:0,inboundMessages:0,spamOrFraud:0,abuseOrSexualHarassment:0,complaints:0,contactRequests:0,knowledgeGaps:0},series:[],customers:[],recommendations:[]};
const dateInput=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function presetDates(preset:Preset){const end=new Date();const start=new Date(end);if(preset==='today')start.setHours(0,0,0,0);else if(preset==='week'){start.setDate(start.getDate()-6);start.setHours(0,0,0,0);}else{start.setDate(start.getDate()-29);start.setHours(0,0,0,0);}return {from:dateInput(start),to:dateInput(end)};}
function instants(from:string,to:string){const start=new Date(`${from}T00:00:00`);const end=new Date(`${to}T00:00:00`);end.setDate(end.getDate()+1);return {from:start.toISOString(),to:end.toISOString()};}
const formatNumber=new Intl.NumberFormat();
const shortDate=(value:string|null)=>value?new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';

export function Analytics({db,view}:{db:SupabaseClient;view:View}){
  const repository=useMemo(()=>new AnalyticsRepository(db),[db]);const initial=useMemo(()=>presetDates('month'),[]);
  const [memberships,setMemberships]=useState<Membership[]>([]),[tenant,setTenant]=useState('');
  const [preset,setPresetState]=useState<Preset>('month'),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[granularity,setGranularity]=useState<AnalyticsGranularity>('day');
  const [report,setReport]=useState<AnalyticsReport>(emptyReport),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[exporting,setExporting]=useState(false),[resetting,setResetting]=useState(false);
  useEffect(()=>{let active=true;void new KnowledgeEditor(db).memberships().then(rows=>{if(active){setMemberships(rows);setTenant(rows[0]?.tenant_id??'');if(!rows.length)setLoading(false);}}).catch(()=>{if(active){setError('Could not load your business access.');setLoading(false);}});return()=>{active=false;};},[db]);
  useEffect(()=>{if(!tenant||(view==='analytics'&&(!from||!to)))return;let active=true;const load=async()=>{setLoading(true);setError('');try{if(view==='recommendations'){const recommendations=await repository.recommendations(tenant);if(active)setReport({...emptyReport,recommendations});}else{const range=instants(from,to);const value=await repository.report(tenant,range.from,range.to,granularity);if(active)setReport(value);}}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}};void load();return()=>{active=false;};},[repository,tenant,from,to,granularity,refresh,view]);
  function setPreset(value:Preset){setPresetState(value);if(value!=='custom'){const dates=presetDates(value);setFrom(dates.from);setTo(dates.to);setGranularity('day');}}
  const membership=memberships.find(row=>row.tenant_id===tenant),business=membership?.name??'Business',canReset=['owner','admin'].includes(membership?.role??'');
  async function download(){setExporting(true);setError('');try{const range=instants(from,to);await repository.download(tenant,range.from,range.to,granularity);}catch(e){setError((e as Error).message);}finally{setExporting(false);}}
  async function resetRecommendations(){
    if(!tenant||resetting||!canReset||!report.recommendations.length||!window.confirm('Reset all current AI recommendations? They will disappear now. New customer activity can create fresh recommendations.'))return;
    setResetting(true);setError('');setNotice('');
    try{await repository.resetRecommendations(tenant);setReport({...emptyReport,recommendations:[]});setNotice('AI recommendations were reset. New customer activity can create fresh recommendations.');window.dispatchEvent(new Event('recommendations-updated'));}
    catch(e){setError((e as Error).message);}finally{setResetting(false);}
  }
  return <main className="content analytics-content">
    <div className="analytics-title"><div><div className="eyebrow">{view==='analytics'?'CHAT PERFORMANCE':'BUSINESS OPPORTUNITIES'}</div><h1>{view==='analytics'?'Analytics':'AI recommendations'}</h1><p className="intro">{view==='analytics'?'See who reached your business and which conversations need attention.':'Turn unanswered customer questions and recurring complaint themes into practical improvements.'}</p></div>{view==='analytics'?<button className="primary export-button" disabled={loading||exporting||!tenant} onClick={()=>void download()}>{exporting?'Preparing Excel…':'Download Excel'}</button>:<button className="secondary delete-button recommendation-reset" title={!canReset?'Owner or admin access is required to reset recommendations.':undefined} disabled={loading||resetting||!canReset||!report.recommendations.length} onClick={()=>void resetRecommendations()}>{resetting?'Resetting…':'Reset'}</button>}</div>
    {view==='analytics'&&<section className="analytics-filter" aria-label="Analytics date filters">
      <div className="period-presets" role="group" aria-label="Quick date range">{([['today','Today'],['week','Last 7 days'],['month','Last 30 days'],['custom','Custom']] as const).map(([id,label])=><button key={id} aria-pressed={preset===id} onClick={()=>setPreset(id)}>{label}</button>)}</div>
      <div className="date-controls"><label>From<input type="date" value={from} max={to} onChange={e=>{setPresetState('custom');setFrom(e.target.value);}}/></label><label>To<input type="date" value={to} min={from} max={dateInput(new Date())} onChange={e=>{setPresetState('custom');setTo(e.target.value);}}/></label><label>Chart interval<select value={granularity} onChange={e=>setGranularity(e.target.value as AnalyticsGranularity)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></label>{memberships.length>1&&<label>Business<select value={tenant} onChange={e=>setTenant(e.target.value)}>{memberships.map(row=><option key={row.tenant_id} value={row.tenant_id}>{row.name}</option>)}</select></label>}<button className="secondary refresh-analytics" disabled={loading} onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>
    </section>}
    {view==='recommendations'&&memberships.length>1&&<div className="recommendation-business"><label>Business<select value={tenant} onChange={e=>setTenant(e.target.value)}>{memberships.map(row=><option key={row.tenant_id} value={row.tenant_id}>{row.name}</option>)}</select></label></div>}
    {notice&&<p className="success" role="status">{notice}</p>}
    {error&&<p className="error" role="alert">{error}</p>}
    {loading?<div className="analytics-loading" role="status"><span/>Loading {view==='analytics'?'analytics':'recommendations'}…</div>:!memberships.length?<p className="notice">Your account needs business access.</p>:view==='analytics'?<AnalyticsOverview report={report} business={business}/>:<Recommendations recommendations={report.recommendations}/>}
  </main>;
}

function AnalyticsOverview({report,business}:{report:AnalyticsReport;business:string}){
  const s=report.summary;const rate=(value:number)=>s.customers?`${Math.round(value/s.customers*100)}% of customers`:'No customers in range';
  const cards=[
    ['Customers reached',s.customers,`${formatNumber.format(s.chats)} chats · ${formatNumber.format(s.inboundMessages)} messages`,'green'],
    ['Spam or fraud',s.spamOrFraud,rate(s.spamOrFraud),'amber'],
    ['Abuse or sexual harassment',s.abuseOrSexualHarassment,rate(s.abuseOrSexualHarassment),'red'],
    ['Complaints',s.complaints,rate(s.complaints),'rose'],
    ['Asked for contact',s.contactRequests,rate(s.contactRequests),'blue'],
  ] as const;
  return <>
    <div className="metric-grid">{cards.map(([label,value,detail,tone])=><article className={`metric-card ${tone}`} key={label}><span>{label}</span><strong>{formatNumber.format(value)}</strong><small>{detail}</small></article>)}</div>
    <div className="chart-grid"><section className="analytics-card trend-card"><header><div><span className="chart-kicker">CUSTOMER ACTIVITY</span><h2>Customers over time</h2></div><div className="chart-legend"><span className="customers">Customers</span><span className="issues">Attention signals</span></div></header>{report.series.length?<TrendChart report={report}/>:<EmptyChart/>}</section><section className="analytics-card mix-card"><span className="chart-kicker">CONVERSATION MIX</span><h2>What customers needed</h2><IssueMix report={report}/></section></div>
    <section className="analytics-card customer-analytics"><header><div><span className="chart-kicker">CUSTOMER DETAIL</span><h2>{business} chat activity</h2></div><span>{report.customers.length} customers with activity or attention signals</span></header>{report.customers.length?<div className="analytics-table-wrap"><table><thead><tr><th>Customer</th><th>Number</th><th>Last contact</th><th>Messages</th><th>Spam / fraud</th><th>Abuse</th><th>Complaints</th><th>Contact requests</th></tr></thead><tbody>{report.customers.map(row=><tr key={row.id}><td><strong dir="auto">{row.name}</strong>{row.username&&<small>@{row.username}</small>}</td><td dir="ltr">{row.phone?`+${row.phone}`:'Not shared'}</td><td>{shortDate(row.lastContact)}</td><td>{row.inboundMessages}</td><td>{flagValue(row.spamOrFraud)}</td><td>{flagValue(row.abuseOrSexualHarassment)}</td><td>{flagValue(row.complaints)}</td><td>{flagValue(row.contactRequests)}</td></tr>)}</tbody></table></div>:<div className="analytics-empty"><span>⌁</span><h3>No chat activity in this period</h3><p>Choose a wider date range when customer messages begin arriving.</p></div>}</section>
  </>;
}
function flagValue(value:number){return value?<span className="table-flag">{value}</span>:<span className="table-zero">0</span>;}
function TrendChart({report}:{report:AnalyticsReport}){const width=720,height=230,pad=24;const values=report.series.flatMap(row=>[row.customers,row.spamOrFraud+row.abuseOrSexualHarassment+row.complaints+row.contactRequests]);const max=Math.max(1,...values);const points=(key:'customers'|'issues')=>report.series.map((row,index)=>{const value=key==='customers'?row.customers:row.spamOrFraud+row.abuseOrSexualHarassment+row.complaints+row.contactRequests;const x=pad+(report.series.length===1?(width-2*pad)/2:index*(width-2*pad)/(report.series.length-1));const y=height-pad-value/max*(height-2*pad);return `${x},${y}`;}).join(' ');return <div className="trend-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Customer and attention signal trend"><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad}/><line x1={pad} x2={width-pad} y1={height/2} y2={height/2}/><polyline className="trend-customers" points={points('customers')}/><polyline className="trend-issues" points={points('issues')}/>{report.series.map((row,index)=>{const x=pad+(report.series.length===1?(width-2*pad)/2:index*(width-2*pad)/(report.series.length-1));return <circle key={row.period} className="trend-dot" cx={x} cy={height-pad-row.customers/max*(height-2*pad)} r="4"><title>{`${shortDate(row.period)}: ${row.customers} customers`}</title></circle>;})}</svg><div className="trend-labels">{report.series.map((row,index)=><span key={row.period} style={{left:`${report.series.length===1?50:index/(report.series.length-1)*100}%`}}>{shortDate(row.period).replace(/, \d{4}/,'')}</span>)}</div></div>;}
function IssueMix({report}:{report:AnalyticsReport}){const items=[['Complaints',report.summary.complaints,'#c86c62'],['Contact requests',report.summary.contactRequests,'#6685a7'],['Spam or fraud',report.summary.spamOrFraud,'#d29a48'],['Abuse',report.summary.abuseOrSexualHarassment,'#a84f45']] as const;const total=items.reduce((sum,item)=>sum+item[1],0);let cursor=0;const gradient=items.map(([,value,color])=>{const start=total?cursor/total*100:0;cursor+=value;const end=total?cursor/total*100:0;return `${color} ${start}% ${end}%`;}).join(',');return <div className="issue-mix"><div className="donut" style={{background:total?`conic-gradient(${gradient})`:'#e7ebe4'}}><div><strong>{total}</strong><span>signals</span></div></div><ul>{items.map(([label,value,color])=><li key={label}><i style={{background:color}}/><span>{label}</span><strong>{value}</strong></li>)}</ul></div>;}
function EmptyChart(){return <div className="empty-chart"><span>Activity will appear here</span></div>;}
function Recommendations({recommendations}:{recommendations:AnalyticsRecommendation[]}){const faq=recommendations.filter(r=>r.kind==='faq_gap'),complaints=recommendations.filter(r=>r.kind==='complaint_theme');return <div className="recommendation-layout"><RecommendationSection title="FAQ opportunities" intro="Only questions the assistant could not answer and escalated for personal follow-up." rows={faq} emptyTitle="No unanswered questions" emptyText="Answered topics and information already handled by the assistant do not appear here."/><RecommendationSection title="Recurring complaint themes" intro="Topics that appeared in more than one AI-classified complaint since the last reset." rows={complaints} emptyTitle="No repeated complaint theme" emptyText="A theme appears after more than one complaint is classified under the same topic."/></div>;}
function RecommendationSection({title,intro,rows,emptyTitle,emptyText}:{title:string;intro:string;rows:AnalyticsRecommendation[];emptyTitle:string;emptyText:string}){return <section className="analytics-card recommendation-section"><header><div><h2>{title}</h2><p>{intro}</p></div><span className="recommendation-count">{rows.length}</span></header>{rows.length?<div className="recommendation-list">{rows.map((row,index)=><article key={`${row.kind}:${row.topic}`}><div className="recommendation-rank">{String(index+1).padStart(2,'0')}</div><div><h3 dir="auto">{row.topic}</h3><p>{row.reason}</p><div className="recommendation-meta"><span>{row.mentions} {row.kind==='faq_gap'?(row.mentions===1?'escalation':'escalations'):'mentions'}</span><span>{row.customers} customers</span><span>Last seen {shortDate(row.lastSeen)}</span></div></div><a className="secondary recommendation-action" href={row.kind==='faq_gap'?'/dashboard':'/dashboard/inbox'}>{row.kind==='faq_gap'?'Review FAQs':'Open inbox'}</a></article>)}</div>:<div className="analytics-empty compact"><span>✓</span><h3>{emptyTitle}</h3><p>{emptyText}</p></div>}</section>;}
